### ISSUE TITLE
Example Notebooks more update needed

### ISSUE THREAD

**Issue by PfisterLB** [klapo/pyfocs#27]
Some errors occurred:
pyfocs_ex1/pyfocs_ex2/pyfocs_ex3
- 'Directories': `dir_dts_data = os.getcwd()` INCORRECT -> the directory is the directory of the notebook, not where the data is located -> definitions are wrong
-> comment/delete the line `os.chdir(dir_dts_data)` in 'Load the configuration file'
-> fix 'Directories': move below 'Load the configuration file'; change to `dir_dts_data = cfg['directories']['local']['dir_pre']` -> the correct directory is then grabbed from the configuration file

pyfocs_ex1:
- 'Example code for checking splices and step-losses': no step loss LAF given in the example so this section doesn't run

pyfocs_ex2:
- 'Uncertainty, noise, and variance' color bars are missing
- delete the section about 'ss' in the notebook or uncomment 'ss' as a core in the 'example_configuration.yml'-file

I will ad issues with pyfocs_ex3 another day

**Comment by klapo** [comment]
I'm closing issue #24 and merging the details from that issue here.

>When code/packages are imported the notebook tries to import btmm_process instead of pyfocs.

**Comment by klapo** [comment]
From issue #8 
> example_configuration.yml:
> for multicore processing the second core 'p2' has to be uncommented

**Comment by klapo** [comment]
Adding that the new pyfocs functionality needs to be included in the example notebooks. The current ones are severely out of date.
