### ISSUE TITLE
Incompatible with xarray v0.19.0 and newer

### ISSUE THREAD

**Issue by jmhuss** [klapo/pyfocs#63]
The calibration step fails and returns:
`TypeError: Using a DataArray object to construct a variable is ambigous, please extract the data using the .data property.`

The error occurs in `data.py`, line 121

![TypeError](https://user-images.githubusercontent.com/60262682/148773498-10b0f5bd-316e-4857-a101-d6785b1cd888.png)

The issue is currently solved by downgrading xarray to v0.18.2

**Comment by klapo** [comment]
This was just fixed in the modernize branch, at least for the cases covered by the tests. I'll close the issue but please let me know if you find any other cases.
