### ISSUE TITLE
Deprecated matplotlib function in dts_plots.py

### ISSUE THREAD

**Issue by jmhuss** [klapo/pyfocs#67]
The `bath_check()` function in dts_plots.py produces the following error:
```
File ~/anaconda3/lib/python3.9/site-packages/pyfocs/dts_plots.py:589, in bath_check(ds, callib, lims_dict, fig_kwargs, title, include_temp, laf_lims)
    587 ax.set_xlim(bath_start - laf_lims, bath_end + laf_lims)
    588 ax.set_ylim(bath_lims["power_anom"])
--> 589 if ax.is_first_col():
    590     ax.set_ylabel(r"$log(\frac{Ps}{Pas}) - \overline{log(\frac{Ps}{Pas})}$")
    591 ax.xaxis.set_major_locator(MultipleLocator(1))

AttributeError: 'Axes' object has no attribute 'is_first_col'
```

The matplotlib functions `is_first_col()` and `is_first_col()` are no longer supported by matplotlib.
The new functionality is be `get_subplotspec().is_first_col()`.
I tried this but it did not solve the issue for me so instead I downgraded to matplotlib v3.4.1, which is the last version to support `is_first_col()` and `is_first_col()`.

**Comment by klapo** [comment]
I'll take a look at it since I am currently updating pyfocs generally. Thanks for catching this issue!
